version: '3.9'
services:
  mysqldb:
    image: mysql:latest
    container_name: bff_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: QqnRxDYneFXz5m8b
      MYSQL_DATABASE: steam_test
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  redis:
    image: redis:latest
    container_name: bff_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - webnet

networks:
  webnet:
volumes:
  db_data:
  mongo_data:
  redis:
    driver: local
